name: XCS234_A2_GPU
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.4.0
  - tk>=8.6.8
  - matplotlib=3.3.4
  - numpy
  - ffmpeg=4.2.2
  - scipy=1.6.2
  - tensorboard=2.5.0
  - pyyaml=5.4.1
  - pip=21.1.3
  - pip:
    - gym==0.18.3
    - cmake==3.20.5; sys_platform != "win32"
    - wget==1.0; sys_platform != "win32"
    - atari-py==0.2.5; sys_platform != "win32"
    - --find-links https://github.com/Kojoley/atari-py/releases 
    - atari-py==1.2.2; sys_platform == "win32"
    - torch==1.10.2